databases:
  - name: tailorpro-db
    plan: starter

services:
  - type: web
    name: tailorpro-backend
    env: docker
    plan: starter
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:your-app-key-here
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: tailorpro-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: tailorpro-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: tailorpro-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: tailorpro-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: tailorpro-db
          property: password

  - type: web
    name: tailorpro-frontend
    env: static
    plan: starter
    buildCommand: "npm install && npm run build"
    staticPublishPath: "build"
